AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ubc-reddit-reporter

  Serverless application with separate Lambda functions for Reddit fetching and analysis

Parameters:
  CategorizationModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    Description: Bedrock model ID to use for sentiment categorization
    AllowedValues:
      - anthropic.claude-3-sonnet-20240229-v1:0
      - anthropic.claude-3-haiku-20240307-v1:0
      - anthropic.claude-3-opus-20240229-v1:0
      - anthropic.claude-v2:1
      - anthropic.claude-v2
      - meta.llama2-13b-chat-v1
      - meta.llama2-70b-chat-v1
      - meta.llama3-8b-instruct-v1:0
      - meta.llama3-70b-instruct-v1:0
      - amazon.titan-text-lite-v1
      - amazon.titan-text-express-v1
      - amazon.titan-text-agile-v1

  SummarizationModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    Description: Bedrock model ID to use for text summarization
    AllowedValues:
      - anthropic.claude-3-sonnet-20240229-v1:0
      - anthropic.claude-3-haiku-20240307-v1:0
      - anthropic.claude-3-opus-20240229-v1:0
      - anthropic.claude-v2:1
      - anthropic.claude-v2
      - meta.llama2-13b-chat-v1
      - meta.llama2-70b-chat-v1
      - meta.llama3-8b-instruct-v1:0
      - meta.llama3-70b-instruct-v1:0
      - amazon.titan-text-lite-v1
      - amazon.titan-text-express-v1
      - amazon.titan-text-agile-v1

  RedditFetchSchedule:
    Type: String
    Default: rate(7 days)
    Description: Schedule expression for Reddit fetching (rate or cron format)
    AllowedValues:
      - rate(7 days)
      - rate(1 day)
      - cron(0 0 ? * SUN *)
      - cron(0 0 ? * MON *)
      - cron(0 0 ? * TUE *)
      - cron(0 0 ? * WED *)
      - cron(0 0 ? * THU *)
      - cron(0 0 ? * FRI *)
      - cron(0 0 ? * SAT *)
      - cron(0 9 ? * MON *)

  AnalysisSchedule:
    Type: String
    Default: rate(7 days)
    Description: Schedule expression for analysis (rate or cron format)
    AllowedValues:
      - rate(7 days)
      - rate(1 day)
      - cron(0 0 ? * SUN *)
      - cron(0 0 ? * MON *)
      - cron(0 0 ? * TUE *)
      - cron(0 0 ? * WED *)
      - cron(0 0 ? * THU *)
      - cron(0 0 ? * FRI *)
      - cron(0 0 ? * SAT *)
      - cron(0 9 ? * MON *)

  EnableRedditFetchSchedule:
    Type: String
    Default: "true"
    Description: Enable or disable the Reddit fetch scheduled event (true/false)
    AllowedValues:
      - "true"
      - "false"

  EnableAnalysisSchedule:
    Type: String
    Default: "true"
    Description: Enable or disable the analysis scheduled event (true/false)
    AllowedValues:
      - "true"
      - "false"

  RedditClientId:
    Type: String
    Default: ""
    Description: Reddit API Client ID (leave empty if not using Reddit API)
    NoEcho: false

  RedditClientSecret:
    Type: String
    Default: ""
    Description: Reddit API Client Secret (leave empty if not using Reddit API)
    NoEcho: true

  RedditUserAgent:
    Type: String
    Default: "scraper"
    Description: Reddit API User Agent string

  RedditSubreddit:
    Type: String
    Default: "UBC"
    Description: Subreddit name to fetch posts from
  
Conditions:
  RedditFetchScheduleEnabled: !Equals [!Ref EnableRedditFetchSchedule, "true"]
  AnalysisScheduleEnabled: !Equals [!Ref EnableAnalysisSchedule, "true"]

Resources:
  # S3 Bucket for storing data
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-data-bucket-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  # IAM Role for Reddit Fetcher (S3 access only)
  RedditFetcherExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt DataBucket.Arn
                  - !Sub '${DataBucket.Arn}/*'

  # IAM Role for Analyzer (S3 + Bedrock access)
  AnalyzerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt DataBucket.Arn
                  - !Sub '${DataBucket.Arn}/*'
        - PolicyName: BedrockAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource:
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/*'

  # Reddit Fetcher Lambda Function
  RedditFetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: reddit_fetcher.lambda_handler
      Role: !GetAtt RedditFetcherExecutionRole.Arn
      Runtime: python3.11
      Timeout: 300
      MemorySize: 512
      Layers:
        - arn:aws:lambda:us-west-2:336392948345:layer:AWSSDKPandas-Python311:13
      Environment:
        Variables:
          REDDIT_CLIENT_ID: !Ref RedditClientId
          REDDIT_CLIENT_SECRET: !Ref RedditClientSecret
          REDDIT_USER_AGENT: !Ref RedditUserAgent
          REDDIT_SUBREDDIT: !Ref RedditSubreddit
          BUCKET_NAME: !Ref DataBucket
          LOG_LEVEL: INFO
      Events:
        RedditFetchSchedule:
          Type: Schedule
          Properties:
            Schedule: !Ref RedditFetchSchedule
            Enabled: !If [RedditFetchScheduleEnabled, true, false]
            Description: Scheduled execution for fetching Reddit posts
      Tags:
        Project: ubc-reddit-reporter
        Function: reddit-fetcher
        Environment: dev

  # Analyzer Lambda Function
  AnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: analyzer.lambda_handler
      Role: !GetAtt AnalyzerExecutionRole.Arn
      Runtime: python3.11
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          BUCKET_NAME: !Ref DataBucket
          LOG_LEVEL: INFO
          CATEGORIZATION_MODEL_ID: !Ref CategorizationModelId
          SUMMARIZATION_MODEL_ID: !Ref SummarizationModelId
          BEDROCK_REGION: !Ref AWS::Region
      Events:
        AnalysisSchedule:
          Type: Schedule
          Properties:
            Schedule: !Ref AnalysisSchedule
            Enabled: !If [AnalysisScheduleEnabled, true, false]
            Description: Scheduled execution for sentiment analysis and summarization
      Tags:
        Project: ubc-reddit-reporter
        Function: analyzer
        Environment: dev

Outputs:
  RedditFetcherFunction:
    Description: "Reddit Fetcher Lambda Function ARN"
    Value: !GetAtt RedditFetcherFunction.Arn
  RedditFetcherFunctionRole:
    Description: "IAM Role for Reddit Fetcher function"
    Value: !GetAtt RedditFetcherExecutionRole.Arn
  AnalyzerFunction:
    Description: "Analyzer Lambda Function ARN"
    Value: !GetAtt AnalyzerFunction.Arn
  AnalyzerFunctionRole:
    Description: "IAM Role for Analyzer function"
    Value: !GetAtt AnalyzerExecutionRole.Arn
  DataBucketName:
    Description: "S3 Bucket Name"
    Value: !Ref DataBucket
  DataBucketArn:
    Description: "S3 Bucket ARN"
    Value: !GetAtt DataBucket.Arn
  RedditFetchSchedule:
    Description: "EventBridge schedule for Reddit fetching"
    Value: !Ref RedditFetchSchedule
  AnalysisSchedule:
    Description: "EventBridge schedule for analysis"
    Value: !Ref AnalysisSchedule
  RedditFetchScheduleEnabled:
    Description: "Whether the Reddit fetch schedule is enabled"
    Value: !Ref EnableRedditFetchSchedule
  AnalysisScheduleEnabled:
    Description: "Whether the analysis schedule is enabled"
    Value: !Ref EnableAnalysisSchedule
